#!/usr/bin/env sh

echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE}" | mysql -u ${MYSQL_USER} -p${MYSQL_PASSWORD} -h ${MYSQL_HOST} > /dev/null 2>&1

CMD="php -f /var/www/html/install.php -- --license_agreement_accepted 'yes' --locale $MAGENTO_LOCALE --timezone '$MAGENTO_TIMEZONE' --default_currency $MAGENTO_DEFAULT_CURRENCY --db_host $MYSQL_HOST --db_name $MYSQL_DATABASE --db_user $MYSQL_USER --db_pass $MYSQL_PASSWORD --url '$MAGENTO_URL' --skip_url_validation 'yes' --use_rewrites 'no' --use_secure 'no' --secure_base_url '' --use_secure_admin 'no' --admin_firstname $MAGENTO_ADMIN_FIRSTNAME --admin_lastname $MAGENTO_ADMIN_LASTNAME --admin_email $MAGENTO_ADMIN_EMAIL --admin_username $MAGENTO_ADMIN_USERNAME --admin_password $MAGENTO_ADMIN_PASSWORD"
eval ${CMD}
