version: '3.0'
services:
    apache:
        build:
            context: ./apache
            args:
                - APP_DIR=${APP_DIR}
        image: apache-magento-1.9
        volumes:
            - magento-app:${APP_DIR}
        ports:
            - ${MAGENTO_PORT}:80
        networks:
            - magento-network
        environment:
            - PHP_HOST=php
            - PHP_PORT=9000
            - APP_DIR=${APP_DIR}
        stdin_open: true
        tty: true
        depends_on:
            - php
    php:
        build:
            context: ./php
            args:
                - APP_DIR=${APP_DIR}
                - XDEBUG_INI=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
                - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
                - HOST_IP=${HOST_IP}
        image: php-magento-1.9
        volumes:
            - magento-app:${APP_DIR}
        entrypoint: /run.sh
        ports:
            - 9000:9000
        networks:
            - magento-network
        environment:
            - MAGENTO_LOCALE=${MAGENTO_LOCALE}
            - MAGENTO_TIMEZONE=${MAGENTO_TIMEZONE}
            - MAGENTO_DEFAULT_CURRENCY=${MAGENTO_DEFAULT_CURRENCY}
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MAGENTO_URL=${MAGENTO_URL}
            - MAGENTO_ADMIN_FIRSTNAME=${MAGENTO_ADMIN_FIRSTNAME}
            - MAGENTO_ADMIN_LASTNAME=${MAGENTO_ADMIN_LASTNAME}
            - MAGENTO_ADMIN_EMAIL=${MAGENTO_ADMIN_EMAIL}
            - MAGENTO_ADMIN_USERNAME=${MAGENTO_ADMIN_USERNAME}
            - MAGENTO_ADMIN_PASSWORD=${MAGENTO_ADMIN_PASSWORD}
        links:
            - db
        stdin_open: true
        tty: true
        depends_on:
            - db
    db:
        image: mysql:5.6.23
        volumes:
            - magento-db:/var/lib/mysql/data
            - ./db/run.sh:/run.sh
        entrypoint: /run.sh
        networks:
            - magento-network
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MAGENTO_DATABASE=${MYSQL_DATABASE}
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8084:80
        networks:
            - magento-network
        links:
            - db

volumes:
    magento-db:
    magento-app:

networks:
    magento-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
