version: '3.0'
services:
    web:
        build:
            context: ./php
            args:
                - APP_DIR=${APP_DIR}
        image: docker-magento-1.9
        ports:
            - ${MAGENTO_PORT}:80
        links:
            - db
    db:
        image: mysql:5.6.23
        volumes:
            - magento-db:/var/lib/mysql/data
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8084:80
        links:
            - db

volumes:
    magento-db:
