version: '3.0'
services:
    apache:
        build:
            context: ./apache
            args:
                - APP_DIR=${APP_DIR}
        image: apache-magento-1.9
        ports:
            - ${MAGENTO_PORT}:80
        networks:
            - magento-network
        environment:
            - PHP_HOST=php
            - PHP_PORT=9000
            - APP_DIR=${APP_DIR}
        stdin_open: true
        tty: true
        depends_on:
            - php
    php:
        build:
            context: ./php
            args:
                - APP_DIR=${APP_DIR}
                - XDEBUG_INI=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
                - XDEBUG_IDEKEY=${XDEBUG_IDEKEY}
                - HOST_IP=${HOST_IP}
        image: php-magento-1.9
        volumes:
            - magento-app:/var/www/app
        ports:
            - 9000:9000
        networks:
            - magento-network
        links:
            - db
        stdin_open: true
        tty: true
    db:
        image: mysql:5.6.23
        volumes:
            - magento-db:/var/lib/mysql/data
        networks:
            - magento-network
        environment:
            - MYSQL_ROOT_PASSWORD=magento
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8084:80
        networks:
            - magento-network
        links:
            - db

volumes:
    magento-db:
    magento-app:

networks:
    magento-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
